require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# This fixes the Google Cast SDK static binary issue
install! 'cocoapods', 
         :disable_input_output_paths => true,
         :deterministic_uuids => false

platform :ios, '14.0'

# Change from use_frameworks! to use_frameworks! :linkage => :static
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
# install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapgoCapacitorJwPlayer', :path => '../../..'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # This is needed for apps with static frameworks
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # Workaround for Google Cast SDK static framework issue
      if target.name == 'google-cast-sdk'
        config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
      end
    end
  end
end
